name: eShopOnWeb Build and Test

# Triggers
on: [push, workflow_dispatch]

# Environment variables
env:
  RESOURCE_GROUP: rg-eshoponweb-rei
  LOCATION: westus2
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: ffba7af0-6e74-4ff3-becd-4bd7912685c6
  WEBAPP_NAME: eshoponweb-webapp53672729

jobs:
  buildandtest:
    name: Build and Test .NET App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload .NET artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload Bicep template
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development
    steps:
      - name: Download .NET artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download Bicep template
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep template exists
        run: |
          if [ ! -f bicep-template/webapp.bicep ]; then
            echo "Bicep template not found: bicep-template/webapp.bicep"
            exit 1
          fi
          ls -la bicep-template

      - name: Deploy infrastructure using Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account set --subscription ${{ env.SUBSCRIPTION_ID }}
            az deployment group create \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --template-file bicep-template/webapp.bicep \
              --parameters webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }} \
              --debug

      - name: Validate artifact exists
        run: |
          if [ ! -f .net-app/app.zip ]; then
            echo "Artifact not found: .net-app/app.zip"
            exit 1
          fi

      - name: Publish Website to WebApp
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deployment source config-zip \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src .net-app/app.zip \
              --debug
